// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vvzxfsvmtxxqcrddyceq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2enhmc3ZtdHh4cWNyZGR5Y2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODY3ODEsImV4cCI6MjA3MTM2Mjc4MX0.tJE9x51rxM-pXcUj52q44YxpGuiB0wgxk5omGjSw8AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
